/*
    Seed de VeiculoVersao - versoes reais de mercado (Brasil) por marca/modelo.
    Padrao de nome: "<motorizacao> <VERSAO EM MAIUSCULO>" (igual Cruze/Agile ja cadastrados).
    Script idempotente: pode ser executado mais de uma vez sem duplicar.
*/
SET NOCOUNT ON;

DECLARE @Versoes TABLE (Marca NVARCHAR(100), Modelo NVARCHAR(100), Versao NVARCHAR(100));

INSERT INTO @Versoes (Marca, Modelo, Versao) VALUES
-- VW/Volkswagen
('VW/Volkswagen','Gol','1.0 CITY'),
('VW/Volkswagen','Gol','1.0 TRENDLINE'),
('VW/Volkswagen','Gol','1.0 COMFORTLINE'),
('VW/Volkswagen','Gol','1.6 HIGHLINE'),
('VW/Volkswagen','Gol','1.6 MSI TRACK'),
('VW/Volkswagen','Gol','1.0 TSI GT'),
('VW/Volkswagen','Fox','1.0 TRENDLINE'),
('VW/Volkswagen','Fox','1.6 CONNECT'),
('VW/Volkswagen','Fox','1.6 COMFORTLINE'),
('VW/Volkswagen','Fox','1.6 HIGHLINE'),
('VW/Volkswagen','Fox','1.6 PEPPER'),
('VW/Volkswagen','Fox','1.6 XTREME'),
('VW/Volkswagen','Parati','1.6 CITY'),
('VW/Volkswagen','Parati','1.6 PLUS'),
('VW/Volkswagen','Parati','1.6 COMFORTLINE'),
('VW/Volkswagen','Parati','1.6 TRACK & FIELD'),
('VW/Volkswagen','Parati','1.8 SUMMER'),
('VW/Volkswagen','Parati','2.0 CROSSOVER'),
('VW/Volkswagen','Voyage','1.0 CITY'),
('VW/Volkswagen','Voyage','1.0 TRENDLINE'),
('VW/Volkswagen','Voyage','1.6 COMFORTLINE'),
('VW/Volkswagen','Voyage','1.6 HIGHLINE'),
('VW/Volkswagen','Voyage','1.6 EVIDENCE'),
('VW/Volkswagen','Voyage','1.6 MSI CONNECT'),
('VW/Volkswagen','Golf','1.0 TSI TRENDLINE'),
('VW/Volkswagen','Golf','1.6 MSI COMFORTLINE'),
('VW/Volkswagen','Golf','1.4 TSI COMFORTLINE'),
('VW/Volkswagen','Golf','1.4 TSI HIGHLINE'),
('VW/Volkswagen','Golf','2.0 TSI GTI'),
('VW/Volkswagen','Golf','2.0 TSI R'),
('VW/Volkswagen','Tiguan','1.4 TSI COMFORTLINE'),
('VW/Volkswagen','Tiguan','1.4 TSI HIGHLINE'),
('VW/Volkswagen','Tiguan','1.4 TSI ALLSPACE COMFORTLINE'),
('VW/Volkswagen','Tiguan','2.0 TSI ALLSPACE HIGHLINE'),
('VW/Volkswagen','Tiguan','2.0 TSI R-LINE'),
-- GM/Chevrolet (Onix; Cruze e Agile ja cadastrados)
('GM/Chevrolet','Onix','1.0 JOY'),
('GM/Chevrolet','Onix','1.0 LS'),
('GM/Chevrolet','Onix','1.0 LT'),
('GM/Chevrolet','Onix','1.4 LT'),
('GM/Chevrolet','Onix','1.4 LTZ'),
('GM/Chevrolet','Onix','1.4 ACTIV'),
('GM/Chevrolet','Onix','1.0 TURBO LTZ'),
('GM/Chevrolet','Onix','1.0 TURBO PREMIER'),
-- Fiat
('Fiat','Palio','1.0 FIRE'),
('Fiat','Palio','1.0 ATTRACTIVE'),
('Fiat','Palio','1.4 ELX'),
('Fiat','Palio','1.4 ATTRACTIVE'),
('Fiat','Palio','1.6 ESSENCE'),
('Fiat','Palio','1.6 SPORTING'),
('Fiat','Siena','1.0 FIRE'),
('Fiat','Siena','1.0 EL'),
('Fiat','Siena','1.4 ELX'),
('Fiat','Siena','1.4 ATTRACTIVE'),
('Fiat','Siena','1.6 ESSENCE'),
('Fiat','Siena','1.8 HLX'),
-- Ford
('Ford','Ka','1.0 S'),
('Ford','Ka','1.0 SE'),
('Ford','Ka','1.0 SE PLUS'),
('Ford','Ka','1.5 SEL'),
('Ford','Ka','1.5 TITANIUM'),
('Ford','Ka','1.5 FREESTYLE'),
('Ford','Fiesta','1.0 S'),
('Ford','Fiesta','1.5 SE'),
('Ford','Fiesta','1.6 SE'),
('Ford','Fiesta','1.6 SEL'),
('Ford','Fiesta','1.6 TITANIUM'),
('Ford','Fiesta','1.0 ECOBOOST TITANIUM'),
-- Honda
('Honda','Civic','1.8 LXS'),
('Honda','Civic','1.8 LXL'),
('Honda','Civic','2.0 EX'),
('Honda','Civic','2.0 EXR'),
('Honda','Civic','2.0 EXL'),
('Honda','Civic','2.0 SPORT'),
('Honda','Civic','1.5 TURBO TOURING'),
('Honda','Fit','1.4 LX'),
('Honda','Fit','1.4 LXL'),
('Honda','Fit','1.5 DX'),
('Honda','Fit','1.5 LX'),
('Honda','Fit','1.5 EX'),
('Honda','Fit','1.5 EXL'),
('Honda','Fit','1.5 PERSONAL'),
-- Hyundai
('Hyundai','HB20','1.0 SENSE'),
('Hyundai','HB20','1.0 COMFORT'),
('Hyundai','HB20','1.0 COMFORT PLUS'),
('Hyundai','HB20','1.0 VISION'),
('Hyundai','HB20','1.6 PREMIUM'),
('Hyundai','HB20','1.0 TURBO EVOLUTION'),
('Hyundai','HB20','1.0 TURBO PLATINUM'),
('Hyundai','Creta','1.6 ATTITUDE'),
('Hyundai','Creta','1.6 SMART'),
('Hyundai','Creta','1.6 PULSE'),
('Hyundai','Creta','2.0 PRESTIGE'),
('Hyundai','Creta','2.0 SPORT'),
('Hyundai','Creta','1.0 TURBO COMFORT'),
('Hyundai','Creta','1.0 TURBO LIMITED'),
('Hyundai','Creta','2.0 ULTIMATE'),
-- Toyota
('Toyota','Corolla','1.6 XLI'),
('Toyota','Corolla','1.8 GLI'),
('Toyota','Corolla','1.8 XEI'),
('Toyota','Corolla','2.0 XEI'),
('Toyota','Corolla','2.0 ALTIS'),
('Toyota','Corolla','2.0 ALTIS PREMIUM'),
('Toyota','Corolla','1.8 ALTIS HYBRID'),
('Toyota','Corolla','2.0 GR-S'),
('Toyota','Hilux','2.7 SR FLEX'),
('Toyota','Hilux','2.7 SRV FLEX'),
('Toyota','Hilux','2.8 SR'),
('Toyota','Hilux','2.8 SRV'),
('Toyota','Hilux','2.8 SRX'),
('Toyota','Hilux','2.8 CONQUEST'),
('Toyota','Hilux','2.8 GR-SPORT'),
-- Nissan
('Nissan','Versa','1.0 S'),
('Nissan','Versa','1.6 S'),
('Nissan','Versa','1.6 SV'),
('Nissan','Versa','1.6 SL'),
('Nissan','Versa','1.6 UNIQUE'),
('Nissan','Versa','1.6 SENSE'),
('Nissan','Versa','1.6 ADVANCE'),
('Nissan','Versa','1.6 EXCLUSIVE'),
('Nissan','Kicks','1.6 S'),
('Nissan','Kicks','1.6 SV'),
('Nissan','Kicks','1.6 SL'),
('Nissan','Kicks','1.6 ADVANCE'),
('Nissan','Kicks','1.6 EXCLUSIVE'),
('Nissan','Kicks','1.6 SPECIAL EDITION'),
-- Mitsubishi
('Mitsubishi','Lancer','1.6 GLX'),
('Mitsubishi','Lancer','2.0 GLS'),
('Mitsubishi','Lancer','2.0 HL'),
('Mitsubishi','Lancer','2.0 GT'),
('Mitsubishi','Lancer','2.0 EVOLUTION'),
('Mitsubishi','Pajero','2.0 TR4'),
('Mitsubishi','Pajero','2.0 TR4 FLEX'),
('Mitsubishi','Pajero','3.2 DAKAR HPE'),
('Mitsubishi','Pajero','3.2 FULL HPE'),
('Mitsubishi','Pajero','2.4 SPORT HPE'),
('Mitsubishi','Pajero','2.4 SPORT HPE-S'),
('Mitsubishi','Pajero','3.0 SPORT GLS'),
-- Jeep
('Jeep','Renegade','1.8 SPORT'),
('Jeep','Renegade','1.8 LONGITUDE'),
('Jeep','Renegade','1.8 LIMITED'),
('Jeep','Renegade','1.3 T270 LONGITUDE'),
('Jeep','Renegade','1.3 T270 SERIE S'),
('Jeep','Renegade','2.0 DIESEL TRAILHAWK'),
('Jeep','Compass','2.0 SPORT'),
('Jeep','Compass','2.0 LONGITUDE'),
('Jeep','Compass','2.0 LIMITED'),
('Jeep','Compass','1.3 T270 LONGITUDE'),
('Jeep','Compass','1.3 T270 LIMITED'),
('Jeep','Compass','1.3 T270 SERIE S'),
('Jeep','Compass','2.0 DIESEL TRAILHAWK'),
-- Peugeot
('Peugeot','208','1.2 LIKE'),
('Peugeot','208','1.5 ACTIVE'),
('Peugeot','208','1.6 ACTIVE PACK'),
('Peugeot','208','1.6 ALLURE'),
('Peugeot','208','1.6 GRIFFE'),
('Peugeot','208','1.6 THP GT'),
('Peugeot','2008','1.6 LIKE'),
('Peugeot','2008','1.6 ALLURE'),
('Peugeot','2008','1.6 GRIFFE'),
('Peugeot','2008','1.6 CROSSWAY'),
('Peugeot','2008','1.6 THP GRIFFE'),
-- Renault
('Renault','Sandero','1.0 AUTHENTIQUE'),
('Renault','Sandero','1.0 EXPRESSION'),
('Renault','Sandero','1.0 LIFE'),
('Renault','Sandero','1.0 ZEN'),
('Renault','Sandero','1.6 DYNAMIQUE'),
('Renault','Sandero','1.6 PRIVILEGE'),
('Renault','Sandero','1.6 INTENSE'),
('Renault','Sandero','1.6 STEPWAY'),
('Renault','Sandero','2.0 RS'),
('Renault','Duster','1.6 EXPRESSION'),
('Renault','Duster','1.6 DYNAMIQUE'),
('Renault','Duster','1.6 ZEN'),
('Renault','Duster','1.6 INTENSE'),
('Renault','Duster','2.0 DYNAMIQUE'),
('Renault','Duster','2.0 TECHROAD'),
('Renault','Duster','1.3 TURBO ICONIC'),
-- Citroen
('Citroen','C3','1.0 LIVE'),
('Citroen','C3','1.2 FEEL'),
('Citroen','C3','1.4 GLX'),
('Citroen','C3','1.5 ORIGINE'),
('Citroen','C3','1.6 TENDANCE'),
('Citroen','C3','1.6 EXCLUSIVE'),
('Citroen','C4 Cactus','1.6 LIVE'),
('Citroen','C4 Cactus','1.6 FEEL'),
('Citroen','C4 Cactus','1.6 FEEL PACK'),
('Citroen','C4 Cactus','1.6 SHINE'),
('Citroen','C4 Cactus','1.6 THP SHINE'),
('Citroen','C4 Cactus','1.6 THP BUSINESS'),
-- Kia
('Kia','Sportage','2.0 LX'),
('Kia','Sportage','2.0 EX'),
('Kia','Sportage','2.0 EX2'),
('Kia','Sportage','2.0 SX'),
('Kia','Sportage','1.6 T-GDI GT LINE'),
('Kia','Cerato','1.6 EX'),
('Kia','Cerato','1.6 SX'),
('Kia','Cerato','2.0 EX'),
('Kia','Cerato','2.0 SX'),
('Kia','Cerato','2.0 SX2'),
-- Chery
('Chery','Tiggo 5x','1.5 T LOOK'),
('Chery','Tiggo 5x','1.5 T TXS'),
('Chery','Tiggo 5x','1.5 T TXS PRO'),
('Chery','Tiggo 5x','1.5 T PRO'),
('Chery','Arrizo 6','1.5 T RXT'),
('Chery','Arrizo 6','1.5 T GSX'),
('Chery','Arrizo 6','1.5 T PRO'),
-- Audi
('Audi','A3','1.4 TFSI ATTRACTION'),
('Audi','A3','1.4 TFSI AMBIENTE'),
('Audi','A3','1.4 TFSI PRESTIGE PLUS'),
('Audi','A3','1.8 TFSI AMBITION'),
('Audi','A3','2.0 TFSI PERFORMANCE BLACK'),
('Audi','A3','2.0 TFSI S3'),
('Audi','Q3','1.4 TFSI ATTRACTION'),
('Audi','Q3','1.4 TFSI AMBIENTE'),
('Audi','Q3','1.4 TFSI PRESTIGE PLUS'),
('Audi','Q3','1.4 TFSI BLACK'),
('Audi','Q3','2.0 TFSI AMBITION QUATTRO'),
('Audi','Q3','2.0 TFSI PERFORMANCE BLACK'),
-- BMW
('BMW','320i','2.0 ACTIVEFLEX'),
('BMW','320i','2.0 SPORT'),
('BMW','320i','2.0 SPORT GP'),
('BMW','320i','2.0 MODERN'),
('BMW','320i','2.0 LUXURY'),
('BMW','320i','2.0 M SPORT'),
('BMW','X1','2.0 SDRIVE18I'),
('BMW','X1','2.0 SDRIVE20I ACTIVEFLEX'),
('BMW','X1','2.0 SDRIVE20I GP'),
('BMW','X1','2.0 SDRIVE20I M SPORT'),
('BMW','X1','2.0 XDRIVE25I SPORT'),
-- Mercedes-Benz
('Mercedes-Benz','Classe A','1.6 A200 URBAN'),
('Mercedes-Benz','Classe A','1.6 A200 STYLE'),
('Mercedes-Benz','Classe A','1.3 A200 ADVANCE'),
('Mercedes-Benz','Classe A','1.3 A200 LAUNCH EDITION'),
('Mercedes-Benz','Classe A','2.0 A250 SPORT'),
('Mercedes-Benz','Classe A','2.0 A35 AMG'),
('Mercedes-Benz','GLA','1.6 GLA200 STYLE'),
('Mercedes-Benz','GLA','1.6 GLA200 ADVANCE'),
('Mercedes-Benz','GLA','1.3 GLA200 PROGRESSIVE'),
('Mercedes-Benz','GLA','1.3 GLA200 LAUNCH EDITION'),
('Mercedes-Benz','GLA','2.0 GLA250 SPORT'),
('Mercedes-Benz','GLA','2.0 GLA45 AMG'),
-- Volvo
('Volvo','XC40','1.5 T4 MOMENTUM'),
('Volvo','XC40','2.0 T4 MOMENTUM'),
('Volvo','XC40','2.0 T5 MOMENTUM'),
('Volvo','XC40','2.0 T5 R-DESIGN'),
('Volvo','XC40','2.0 T5 INSCRIPTION'),
('Volvo','XC60','2.0 T5 MOMENTUM'),
('Volvo','XC60','2.0 T5 R-DESIGN'),
('Volvo','XC60','2.0 T5 INSCRIPTION'),
('Volvo','XC60','2.0 T6 INSCRIPTION'),
('Volvo','XC60','2.0 T8 R-DESIGN'),
('Volvo','XC60','2.0 D5 MOMENTUM'),
-- Land Rover
('Land Rover','Range Rover Evoque','2.0 PURE'),
('Land Rover','Range Rover Evoque','2.0 PRESTIGE'),
('Land Rover','Range Rover Evoque','2.0 SE DYNAMIC'),
('Land Rover','Range Rover Evoque','2.0 HSE DYNAMIC'),
('Land Rover','Range Rover Evoque','2.0 R-DYNAMIC SE'),
('Land Rover','Range Rover Evoque','2.0 D180 R-DYNAMIC'),
('Land Rover','Discovery Sport','2.0 S'),
('Land Rover','Discovery Sport','2.0 SE'),
('Land Rover','Discovery Sport','2.0 HSE'),
('Land Rover','Discovery Sport','2.0 HSE LUXURY'),
('Land Rover','Discovery Sport','2.0 R-DYNAMIC SE'),
('Land Rover','Discovery Sport','2.0 D180 SE');

-- Avisa se algum par marca/modelo do script nao existe no banco
SELECT DISTINCT 'MODELO NAO ENCONTRADO: ' + v.Marca + ' / ' + v.Modelo AS Aviso
FROM @Versoes v
WHERE NOT EXISTS (
    SELECT 1 FROM VeiculoModelo mo
    JOIN veiculoMarcas ma ON ma.Id = mo.VeiculoMarcaId
    WHERE mo.Nome = v.Modelo AND ma.Nome = v.Marca);

INSERT INTO VeiculoVersao (Nome, VeiculoModeloId)
SELECT v.Versao, mo.Id
FROM @Versoes v
JOIN VeiculoModelo mo ON mo.Nome = v.Modelo
JOIN veiculoMarcas ma ON ma.Id = mo.VeiculoMarcaId AND ma.Nome = v.Marca
WHERE NOT EXISTS (
    SELECT 1 FROM VeiculoVersao ex
    WHERE ex.VeiculoModeloId = mo.Id AND ex.Nome = v.Versao);

SELECT @@ROWCOUNT AS VersoesInseridas;
